version: "3.8"

services:
  mysql-todolist:
    image: mysql:8.0
    container_name: mysql_todolist
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todolist
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  springboot:
    build: .
    container_name: springboot-container-todolist
    depends_on:
      - mysql-todolist
    environment:
      MYSQL_HOST: mysql-todolist
      MYSQL_DB: todolist
      MYSQL_USER: root
    ports:
      - "8080:8080"

volumes:
  mysql-data:
